#playbook.yaml
---
- name: Get hostname and IP address of Ubuntu hosts
  hosts: ubuntusvrs
  gather_facts: yes
  tasks:
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"