---
- name: Ansible Vault playbook
  hosts: localhost
  gather_facts: false

  tasks:
  - name: show secret
    debug:
      var: my_secret
    no_log: true
  - name: show secret 1
    debug:
      var: nextvar
    #no_log: true
